// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2rymUJP6FHQzvqhtcOGgw8HknEOKZHKA',
    appId: '1:751827017922:web:3b6454f57683b9c64c9b5b',
    messagingSenderId: '751827017922',
    projectId: 'projet3-log3900-v2',
    authDomain: 'projet3-log3900-v2.firebaseapp.com',
    databaseURL: 'https://projet3-log3900-v2-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-log3900-v2.appspot.com',
    measurementId: 'G-1LTR0G6XYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFljggXnOHreyAbdnajVL4yVm1uN2p2GI',
    appId: '1:751827017922:android:028129b597da45064c9b5b',
    messagingSenderId: '751827017922',
    projectId: 'projet3-log3900-v2',
    databaseURL: 'https://projet3-log3900-v2-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-log3900-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8rDNJV55ijPavs6tAMVc9-rxPSUvVCg',
    appId: '1:751827017922:ios:eed0e575d74d760a4c9b5b',
    messagingSenderId: '751827017922',
    projectId: 'projet3-log3900-v2',
    databaseURL: 'https://projet3-log3900-v2-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-log3900-v2.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8rDNJV55ijPavs6tAMVc9-rxPSUvVCg',
    appId: '1:751827017922:ios:5826a5b2f422df054c9b5b',
    messagingSenderId: '751827017922',
    projectId: 'projet3-log3900-v2',
    databaseURL: 'https://projet3-log3900-v2-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-log3900-v2.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
